version: "v1"
author: "Nodnod77"
title: "OS Operating systems 2024-2"
version: "27-August-2024"
copyright: "2024"
githublink: "https://github.com/Nodnod77/os242"
githubpagelink: "https://Nodnod77.github.io/os242/"
loglink: "/TXT/mylog.txt"
encoding: "UTF-8"
copyright: "2024"
github: [metadata]
